name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: https://github.com/JaiGanesh-N-V/simple.git#6512a6cff49e937b472664b528394bdef89a8d6c
          push: true
          tags: - jaiganeshnv007/clockbox:latest
