name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.7.1
            
      -
        name: Build and push
        uses: docker/setup-buildx-action@v3.7.1
        with:
          push: true
          tags: user/app:latest      
